//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CRUDDBEntities : DbContext
    {
        public CRUDDBEntities()
            : base("name=CRUDDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<setupCompanyA> setupCompanyAs { get; set; }
    
        public virtual ObjectResult<spWebFillRpt_Result> spWebFillRpt(string rptType, string fillParam1, string fillParam2, string fillParam3, string fillParam4, string companyID, string userID)
        {
            var rptTypeParameter = rptType != null ?
                new ObjectParameter("rptType", rptType) :
                new ObjectParameter("rptType", typeof(string));
    
            var fillParam1Parameter = fillParam1 != null ?
                new ObjectParameter("fillParam1", fillParam1) :
                new ObjectParameter("fillParam1", typeof(string));
    
            var fillParam2Parameter = fillParam2 != null ?
                new ObjectParameter("fillParam2", fillParam2) :
                new ObjectParameter("fillParam2", typeof(string));
    
            var fillParam3Parameter = fillParam3 != null ?
                new ObjectParameter("fillParam3", fillParam3) :
                new ObjectParameter("fillParam3", typeof(string));
    
            var fillParam4Parameter = fillParam4 != null ?
                new ObjectParameter("fillParam4", fillParam4) :
                new ObjectParameter("fillParam4", typeof(string));
    
            var companyIDParameter = companyID != null ?
                new ObjectParameter("CompanyID", companyID) :
                new ObjectParameter("CompanyID", typeof(string));
    
            var userIDParameter = userID != null ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spWebFillRpt_Result>("spWebFillRpt", rptTypeParameter, fillParam1Parameter, fillParam2Parameter, fillParam3Parameter, fillParam4Parameter, companyIDParameter, userIDParameter);
        }
    }
}
