//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class setupCompanyA
    {
        public string uCompanyID { get; set; }
        public string uCompanyName { get; set; }
        public string uCompanyAdd1 { get; set; }
        public string uCompanyAdd2 { get; set; }
        public string uCompanyPhone { get; set; }
        public string uCompanyTag { get; set; }
        public Nullable<double> uCurrentPO { get; set; }
        public string FYBegMD { get; set; }
        public string FYEndMD { get; set; }
        public Nullable<System.DateTime> FYBegDt { get; set; }
        public Nullable<System.DateTime> FYEndDt { get; set; }
        public Nullable<System.DateTime> sysBegDt { get; set; }
        public Nullable<System.DateTime> sysEndDt { get; set; }
        public string uMultiCurrency { get; set; }
        public string uActive { get; set; }
    }
}
